### ISSUE TITLE
Integrate E2E testing

### ISSUE THREAD

**Issue by larkox** [mattermost/mattermost-plugin-todo#124]
Following a similar design as in the [Incident Response Plugin](https://github.com/mattermost/mattermost-plugin-incident-response/tree/master/tests-e2e) integrate Cypress E2E testing for this plugin.

At least one simple test case has to be added to make sure the system works.

**Comment by jeromegrosse** [comment]
I can give it a shot!

**Comment by larkox** [comment]
Thanks @jeromegrosse ! If you need anything, do not hesitate to ask!

**Comment by rahulsuresh-git** [comment]
Is this still open? I was wondering of introducing Playwright for E2E tests as recommended here (https://developers.mattermost.com/contribute/more-info/desktop/testing/). Any thoughts? @larkox @mickmister

**Comment by mickmister** [comment]
@rahulsuresh-git Certainly this issue is still open :+1:

Using playwright sounds good to me. There are some existing tests in the GitHub plugin that can be used for inspiration https://github.com/mattermost/mattermost-plugin-github/tree/master/e2e/playwright

Thanks for your interest in contributing @rahulsuresh-git!

**Comment by rahulsuresh-git** [comment]
Sure, thank you! I'll get at it right away.
It's good to be back at contributing to Mattermost. I'll get back to you in case of any questions :)
