### ISSUE TITLE
Focus stays in the main window when assignment modal is opened

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-todo#173]
When I open the modal to assign a To Do to someone, the focus does not move. 
When I type to search for a user the search does not respond and if i hit the `D` keystroke (or any other shortcut) I can see that I'm manipulating the data in the Todo list behind the modal.

Steps:
- Create a ToDo not assigned to anyone
- Click to assign the ToDO
- Without touching the mouse to manually move the focus type `D` to search for `Dylan`   
**Observed** Search does not have the focus and I can see that I've deleted my ToDo that the assign modal is open for

**Comment by mickmister** [comment]
@asaadmahmood Would you happen to know of a quick/proper fix for this issue? It seems it was introduced in your PR here https://github.com/mattermost/mattermost-plugin-todo/pull/161

**Comment by asaadmahmood** [comment]
@mickmister Not sure of a proper fix, but a quick fix would be to close the menu when the assign modal is open.
I can't repro this if you click on the assign menu item, but when you use the shortcut `a` to open the assign modal, then this issue occurs because when opening the menu with the shortcut, the menu doesn't closes.

@DHaussermann Are you sure this repros when you click on the assign option, or only when you use the shortcut (`a`) to open assign modal?

**Comment by mickmister** [comment]
Fixed with https://github.com/mattermost/mattermost-plugin-todo/pull/174
