### ISSUE TITLE
Todo can get stuck if not careful

### ISSUE THREAD

**Issue by nitlott** [mattermost/mattermost-plugin-todo#200]
If you create a new todo so it is in your own list and then edit it and assign it to your self (by misstake), it gets permanently stuck.
You can see it in "sent todos" but you cant see it in "my todos" hence you can never complete the task, you cant decline it as you already automatically accepted your own todo when its created.
Also cant re-assign it to someone else as i guess it is waiting for you to accept it again which you cant as you already own it.

How to solve this little pickle?

**Comment by mickmister** [comment]
@asaadmahmood Do you have any thoughts on the UX flow described in this ticket? It seems assigning a todo to yourself gets the data in a bad state. Should we disallow self-assign, or handle this case of self-assign differently?

**Comment by asaadmahmood** [comment]
@mickmister Can we just do nothing if a person assigns this to himself?

**Comment by mickmister** [comment]
@asaadmahmood Do you mean we should disable the ability to assign yourself?

**Comment by asaadmahmood** [comment]
Yes, but not visually on the frontend, because any task that's assigned to you lands in your own todo column, so assigning to should basically do nothing. But since we have an assign button, even if a user assigns to todo to himself, can we leave the assignee empty on the addTodo function and just do nothing?

**Comment by rennhak** [comment]
Stuck with the same problem. Wondering on how to remove the stuck task at least.

**Comment by mickmister** [comment]
> Stuck with the same problem. Wondering on how to remove the stuck task at least.

@rennhak This is pretty inconvenient though I was able to get this to work:

With the browser network tab open:
- use the side panel of the todo plugin to edit the todo's title
- copy the `change_assignment` request by right-clicking and selecting "copy as fetch" or "copy as curl" if you prefer that
- change the url from `change_assignment` to `remove`
- perform the request with this change

The todo should then disappear from the list after this is done. Please let me know if this works out. I agree this bug is unfortunately easy to accidentally produce at the moment. I'll see if it's a simple fix and get the fix pushed on here if so

**Comment by rennhak** [comment]
Thanks for the help @mickmister
