### ISSUE TITLE
Can't active plugin

### ISSUE THREAD

**Issue by rain9x** [mattermost/mattermost-plugin-todo#201]
Hi everybody,
I'm can't active this plugin, it show err message as bellow:

`This plugin failed to start. unable to start plugin: com.mattermost.plugin-todo: unable to generate a checksum for the plugin plugins/com.mattermost.plugin-todo: read plugins/com.mattermost.plugin-todo: is a directory`

Can anyone help to solve this problem? Thanks!

**Comment by mickmister** [comment]
Hi @rain9x, what architecture is your server running on, and what Mattermost server version is running? This error you're seeing usually happens when the plugin was not compiled for the specific arch running the server.

https://github.com/mattermost/mattermost-plugin-todo/blob/b5d7044abe29c79a94acac6cbcbf289d42271b2a/plugin.json#L12-L14

If you're using an OS other than ones listed above, or an `ARM` processor, I don't think this plugin will work currently.

**Comment by rain9x** [comment]
Thanks @mickmister,
I'm using macbook M1 and I added 
` "linux-arm64": "server/dist/plugin-linux-arm64",
darwin-arm64": "server/dist/plugin-darwin-arm64
`
